### PR TITLE
don't depend on window.ga till it's actually needed

### LINKED ISSUE #5986: Drop in GA traffic
**Summary**
We are seeing a drop in GA after the react front-end launch which is inconsistent with other data sources (search console in this case)

**Steps To Reproduce (STR)**
1. Go to GA
2. compare traffic before and after the launch

How can we ensure that we are still collecting as much telemetry as before?

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #5986

### CODE REVIEW

File: kuma/javascript/src/ga-provider.jsx [hunk 1]
```diff
@@ -4,9 +4,13 @@ import { useContext, useEffect, useState } from 'react';
 
 export type GAFunction = (...any) => void;
 
-const noop: GAFunction = () => {};
+function ga(...args) {
+    if (typeof window === 'object' && typeof window.ga === 'function') {
```
Comment (escattone) [inline kuma/javascript/src/ga-provider.jsx]: I'm wondering, if in the future we should consider making this "Ghostery"-proof like we do [here](https://github.com/mdn/kuma/blob/ea715ffdce74c9016854e74b5f28a25ef3f4d830/kuma/static/js/analytics.js#L40) in `kuma/static/js/analytics.js`? Something to think about, but not for this PR.
