### PR TITLE
Privacy checkbox hidden with JS disabled

### LINKED ISSUE #5977: [Newsletter] Privacy checkbox hidden when JS disabled
**Summary**

The privacy checkbox is hidden for users with JS disabled on the newsletter signup form.

**Steps To Reproduce (STR)**

Go to any page with a newsletter signup form with JS disabled in the browser

1. The privacy checkbox is hidden
2. Clicking on submit will no submit the form as the privacy field is required, but the user will not be aware of the missing field

**Expected behavior**

Privacy checkbox should be visible for users with JS disabled. Generally, in these cases the preferred pattern is to make everything essential visible and then visually hide elements via JS by toggling the `hidden` class

### PR DESCRIPTION
**Pull request by schalkneethling**
When JavaScript is disabled or failed to execute the privacy checkbox field is hidden. This makes submitting the form impossible as this is a required field, but is not accessible via the UI.

The pull requests address the issue:

### With JS disabled

Screenshot 2020-03-30 at 14 43 10

### With JS enabled

Screenshot 2020-03-30 at 14 44 03

### With JS disabled

Screenshot 2020-03-30 at 14 39 58

### With JS enabled

Screenshot 2020-03-30 at 14 40 44

@mindy r?

fixes #5977

### CODE REVIEW

File: kuma/javascript/src/newsletter.jsx [hunk 1]
```diff
@@ -145,6 +145,9 @@ export default function Newsletter() {
         if (disableNewsletter) {
             setShowNewsletter(false);
         }
+        // if JS is enabled client-side, hide the privacy checkbox until
+        // the email input field receive focus
+        setShowPrivacyCheckbox(false);
```
Comment (peterbe) [inline kuma/javascript/src/newsletter.jsx]: Beyond the checkbox, does signing up work at all with JS disabled?

Comment (schalkneethling) [reply kuma/javascript/src/newsletter.jsx]: Technically yes, as it will post to `https://www.mozilla.org/en-US/newsletter/`
